# Generated by Django 5.1.3 on 2025-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='merkle_root',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
