# Generated by Django 5.1.3 on 2025-01-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transaction_status_alter_block_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
