# Generated by Django 5.1.3 on 2025-01-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_transaction_status_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('mined', 'Mined')], default='pending', max_length=10),
        ),
    ]
