# Generated by Django 5.1.3 on 2025-01-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hash',
        ),
    ]
