# Generated by Django 5.1.3 on 2025-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
